version: '3.9'

services:
  dev:
    container_name: nestjs_api_dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - db

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=development
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data\

  redis:
    image: "redis:alpine"


